document.documentElement.classList.add('js');
const icons={battery:'<svg viewBox="0 0 24 24"><rect x="2" y="7" width="18" height="10" rx="2"/><path d="M22 10v4M7 10v4m-2-2h4"/></svg>',engine:'<svg viewBox="0 0 24 24"><path d="M7 9h10l2 3v5H5v-6l2-2Zm3 0V6h4v3M8 17v2m8-2v2M2 12h3m14 0h3"/></svg>',bolt:'<svg viewBox="0 0 24 24"><path d="m13 2-8 12h7l-1 8 8-12h-7l1-8Z"/></svg>',disc:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="3"/><path d="M12 3v6m0 6v6M3 12h6m6 0h6"/></svg>',tire:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><path d="m6 6 3 3m6 6 3 3m0-12-3 3m-6 6-3 3"/></svg>',tool:'<svg viewBox="0 0 24 24"><path d="M14 6a4 4 0 0 0-5-4l2.5 2.5-3 3L6 5a4 4 0 0 0 4 5L4 16l4 4 6-6a4 4 0 0 0 5-5l-2.5 2.5-3-3L16 6Z"/></svg>',search:'<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>'};
icons.traction=icons.tire;
const symptoms=['Check Hybrid System warning','Reduced fuel economy','Battery warning lights','Engine misfires or rough running','Brake warnings','Electrical problems','Overheating or unusual noises'];
document.querySelector('#symptoms').innerHTML=symptoms.map((x,i)=>`<div><span>${String(i+1).padStart(2,'0')}</span><p>${x}</p></div>`).join('');
const services=[['battery','Hybrid Battery Service','Testing, diagnosis, repair, and replacement options based on what the battery actually needs.'],['engine','Engine Repair','Diagnosis and repair for rough running, misfires, overheating, and related engine concerns.'],['bolt','Hybrid Electrical Diagnostics','Systematic troubleshooting for warning lights, charging concerns, and high-voltage system faults.'],['disc','Brake Service','Inspection and service for hybrid braking systems, friction brakes, and warning indicators.'],['traction','Traction Control Diagnostics','Diagnosis of traction-control warning lights, wheel-speed sensors, and stability-system faults.'],['tool','Preventive Maintenance','Practical routine maintenance to help your vehicle stay reliable as the miles add up.']];
document.querySelector('#serviceGrid').innerHTML=services.map((s,i)=>`<article class="service-card ${i===0?'featured':''}"><div class="icon icon-${s[0]}" aria-hidden="true">${icons[s[0]]}</div><span>0${i+1}</span><h3>${s[1]}</h3><p>${s[2]}</p><a href="#contact" aria-label="Request ${s[1]}">Request service →</a></article>`).join('');
const models=[['Toyota hybrids','Battery, engine, brakes & electrical.'],['Toyota general repair','Service for supported non-hybrid models.'],['Honda','Service for supported non-hybrid models.'],['Lexus','Hybrid expertise & general repair.'],['Scion','Diagnostics, maintenance & repair.'],['Hyundai hybrids','Diagnostics, maintenance & repair.'],['Kia hybrids','Diagnostics, maintenance & repair.'],['Hybrid diagnostics','Battery, warning-light & electrical testing.']];
document.querySelector('#models').innerHTML=models.map((m)=>`<article class="model-card"><h3>${m[0]}</h3><p>${m[1]}</p><a href="#contact">View supported models <span aria-hidden="true">→</span></a></article>`).join('');
const faq=[['Do you only service the Toyota Prius?','No. We service Toyota, Honda, Lexus, and Scion vehicles, plus Toyota, Hyundai, and Kia hybrids. We do not service European vehicles. Contact us if you are unsure whether your model is supported.'],['Can you diagnose a “Check Hybrid System” warning?','Yes, Hybrid 310 offers diagnostics for hybrid-system warnings. The message can point to several possible causes, so the vehicle must be tested before repair options are recommended.'],['Do you repair or replace hybrid batteries?','We diagnose hybrid battery concerns and can discuss repair or replacement based on test results, vehicle condition, and available options.'],['Do you work on high-mileage Prius vehicles?','Yes. We understand that many Prius vehicles remain useful at high mileage. We evaluate the current problem and explain practical options without making unsupported promises.'],['How do I schedule an appointment?','Call 714-650-9606 or 424-474-3334, or send the appointment-request form below. Your appointment is confirmed only after the shop contacts you with availability.'],['Do you offer service in Spanish?','Spanish service is intended to be available. Please confirm language availability when you call or request your appointment.']];
document.querySelector('#accordion').innerHTML=faq.map((x,i)=>`<details ${i===0?'open':''}><summary>${x[0]}<span></span></summary><p>${x[1]}</p></details>`).join('');
const menu=document.querySelector('.menu'),nav=document.querySelector('#nav'); menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open')}); nav.querySelectorAll('a').forEach(a=>a.onclick=()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')});
const form=document.querySelector('#appointment');form.addEventListener('submit',()=>{const btn=form.querySelector('.submit'),status=form.querySelector('.form-status');btn.disabled=true;status.className='form-status sending';status.textContent=currentLang==='es'?'Enviando solicitud de forma segura…':'Securely sending your request…'});form.querySelectorAll('input,select,textarea').forEach(x=>x.addEventListener('invalid',()=>{x.closest('label')?.classList.add('invalid');const status=form.querySelector('.form-status');status.className='form-status error';status.textContent=currentLang==='es'?'Completa el campo obligatorio resaltado.':'Please complete the highlighted required field.'}));
document.querySelector('#year').textContent=new Date().getFullYear();
document.querySelectorAll('.service-card a,.map').forEach(link=>link.removeAttribute('aria-label'));

const es={
'Skip to content':'Saltar al contenido','Services':'Servicios','Vehicles':'Vehículos','Why us':'Por qué elegirnos','Reviews':'Reseñas','Contact':'Contacto','Schedule service':'Programar servicio','Call Hybrid 310':'Llama a Hybrid 310','Call now':'Llama ahora',
'Independent hybrid repair · Hawthorne, CA':'Reparación independiente de híbridos · Hawthorne, CA','Hybrid specialists':'Especialistas en híbridos','who know your':'que conocen tu','Clear diagnostics and dependable hybrid repair, plus general service for select Toyota, Honda, Lexus, and Scion vehicles.':'Diagnósticos claros y reparación confiable de híbridos, además de servicio general para ciertos vehículos Toyota, Honda, Lexus y Scion.','Diagnostics & repair':'Diagnóstico y reparación','Your local shop':'Tu taller local','Hybrid + general':'Híbridos + servicio general','Supported makes below':'Marcas atendidas abajo',
'Start with the symptom':'Comienza con el síntoma','Your hybrid is telling you something.':'Tu híbrido te está diciendo algo.','Warning lights, rough running, or lost fuel economy can have more than one cause. We diagnose the system first, then explain what we find.':'Las luces de advertencia, el funcionamiento irregular o la pérdida de rendimiento pueden tener varias causas. Primero diagnosticamos el sistema y después explicamos lo que encontramos.','Check Hybrid System warning':'Aviso “Check Hybrid System”','Reduced fuel economy':'Menor rendimiento de combustible','Battery warning lights':'Luces de advertencia de batería','Engine misfires or rough running':'Fallas de encendido o motor irregular','Brake warnings':'Avisos de frenos','Electrical problems':'Problemas eléctricos','Overheating or unusual noises':'Sobrecalentamiento o ruidos inusuales',
'Specialized service':'Servicio especializado','One shop. The whole hybrid system.':'Un taller. Todo el sistema híbrido.','From high-voltage battery diagnostics to brakes and traction control, we look at how the vehicle works as a complete system.':'Desde el diagnóstico de la batería de alto voltaje hasta los frenos y el control de tracción, evaluamos el vehículo como un sistema completo.','Hybrid Battery Service':'Servicio de batería híbrida','Testing, diagnosis, repair, and replacement options based on what the battery actually needs.':'Pruebas, diagnóstico, reparación y opciones de reemplazo según lo que realmente necesita la batería.','Engine Repair':'Reparación de motor','Diagnosis and repair for rough running, misfires, overheating, and related engine concerns.':'Diagnóstico y reparación de marcha irregular, fallas de encendido, sobrecalentamiento y problemas relacionados.','Hybrid Electrical Diagnostics':'Diagnóstico eléctrico híbrido','Systematic troubleshooting for warning lights, charging concerns, and high-voltage system faults.':'Diagnóstico sistemático de luces de advertencia, problemas de carga y fallas de alto voltaje.','Brake Service':'Servicio de frenos','Inspection and service for hybrid braking systems, friction brakes, and warning indicators.':'Inspección y servicio de sistemas de frenado híbrido, frenos de fricción e indicadores.','Preventive Maintenance':'Mantenimiento preventivo','Practical routine maintenance to help your vehicle stay reliable as the miles add up.':'Mantenimiento práctico para conservar la confiabilidad de tu vehículo con el paso de las millas.','General Vehicle Repair':'Reparación general','Diagnosis and repair for supported Toyota, Honda, Lexus, Scion, Hyundai hybrid, and Kia hybrid vehicles.':'Diagnóstico y reparación para Toyota, Honda, Lexus y Scion, además de híbridos Hyundai y Kia.','Request service →':'Solicitar servicio →',
'Vehicles we service':'Vehículos que atendemos','Hybrid expertise. Select general repair.':'Experiencia híbrida. Reparación general selecta.','We service Toyota hybrids, Hyundai hybrids, Kia hybrids, and Lexus vehicles, plus regular Toyota, Honda, and Scion models. We do not service European vehicles.':'Atendemos híbridos Toyota, Hyundai y Kia, vehículos Lexus y modelos convencionales Toyota, Honda y Scion. No atendemos vehículos europeos.','Confirm your vehicle':'Confirma tu vehículo','HYBRID SERVICE':'SERVICIO HÍBRIDO','GENERAL SERVICE':'SERVICIO GENERAL','HYBRID + GENERAL':'HÍBRIDO + GENERAL','NOT SERVICED':'NO ATENDEMOS','Toyota hybrids':'Híbridos Toyota','Toyota (non-hybrid)':'Toyota (no híbrido)','Honda (non-hybrid)':'Honda (no híbrido)','Hyundai hybrids':'Híbridos Hyundai','Kia hybrids':'Híbridos Kia','European vehicles':'Vehículos europeos','Please contact another qualified shop.':'Comunícate con otro taller calificado.',
'Why Hybrid 310':'Por qué Hybrid 310','The right repair starts with the right diagnosis.':'La reparación correcta comienza con el diagnóstico correcto.','Hybrid vehicles deserve more than guesswork. We combine model-specific familiarity with straight answers, so you can make a practical decision for your car.':'Los vehículos híbridos merecen más que suposiciones. Combinamos experiencia específica con respuestas claras para que tomes una decisión práctica.','Hybrid-focused experience':'Experiencia en híbridos','Familiarity with hybrid systems and the common problems Prius owners encounter.':'Conocimiento de sistemas híbridos y problemas comunes del Prius.','Clear diagnostics':'Diagnósticos claros','We start by identifying the cause instead of treating a warning light as the answer.':'Primero identificamos la causa, no tomamos una luz como respuesta.','Practical recommendations':'Recomendaciones prácticas','Repair options explained in plain language, with your vehicle and priorities in mind.':'Opciones explicadas claramente, considerando tu vehículo y prioridades.','High-mileage perspective':'Experiencia con alto millaje','Thoughtful options for reliable hybrids that have already traveled a long way.':'Opciones razonables para híbridos confiables con muchas millas.','Local, personal service':'Servicio local y personal','Direct communication from an independent Hawthorne repair shop.':'Comunicación directa de un taller independiente en Hawthorne.','Whole-vehicle thinking':'Visión integral','Battery, engine, brakes, and electrical systems considered together.':'Evaluamos juntos la batería, el motor, los frenos y los sistemas eléctricos.',
'What to expect':'Qué esperar','A clear path back to the road.':'Un camino claro para volver a la carretera.','Four simple steps, with diagnosis before decisions.':'Cuatro pasos sencillos, con diagnóstico antes de decidir.','Contact the shop':'Contacta el taller','Call or send an appointment request.':'Llama o envía una solicitud de cita.','Bring in your hybrid':'Trae tu híbrido','Tell us what you’re noticing.':'Cuéntanos qué has notado.','Review the diagnosis':'Revisa el diagnóstico','We explain findings and practical options.':'Explicamos los resultados y las opciones prácticas.','Approve the repair':'Autoriza la reparación','Choose how you want to move forward.':'Elige cómo deseas continuar.',
'Customer reviews':'Reseñas de clientes','What drivers have shared.':'Lo que han compartido los conductores.','Selected excerpts from Google reviews supplied by the business. Visit Google for the complete, current review history.':'Extractos seleccionados de reseñas de Google proporcionadas por el negocio. Visita Google para ver el historial completo y actual.','Read all reviews on Google':'Lee todas las reseñas en Google','Schedule your visit':'Programa tu visita','Google review · 8 months ago':'Reseña de Google · hace 8 meses','Google review · 2 years ago':'Reseña de Google · hace 2 años','Google review · 3 years ago':'Reseña de Google · hace 3 años','Google review · 4 years ago':'Reseña de Google · hace 4 años',
'Common questions':'Preguntas frecuentes','Before you bring it in.':'Antes de traer tu vehículo.','Don’t see your question? Call us and we’ll help confirm whether we’re the right shop for your vehicle.':'¿No encuentras tu pregunta? Llámanos y confirmaremos si somos el taller adecuado.','Do you only service the Toyota Prius?':'¿Solo atienden el Toyota Prius?','No. We service Toyota, Honda, Lexus, and Scion vehicles, plus Toyota, Hyundai, and Kia hybrids. We do not service European vehicles. Contact us if you are unsure whether your model is supported.':'No. Atendemos Toyota, Honda, Lexus y Scion, además de híbridos Toyota, Hyundai y Kia. No atendemos vehículos europeos. Contáctanos si tienes dudas.','Can you diagnose a “Check Hybrid System” warning?':'¿Pueden diagnosticar un aviso “Check Hybrid System”?','Yes, Hybrid 310 offers diagnostics for hybrid-system warnings. The message can point to several possible causes, so the vehicle must be tested before repair options are recommended.':'Sí. El aviso puede tener varias causas, por lo que debemos probar el vehículo antes de recomendar opciones.','Do you repair or replace hybrid batteries?':'¿Reparan o reemplazan baterías híbridas?','We diagnose hybrid battery concerns and can discuss repair or replacement based on test results, vehicle condition, and available options.':'Diagnosticamos la batería y explicamos opciones de reparación o reemplazo según las pruebas y el estado del vehículo.','Do you work on high-mileage Prius vehicles?':'¿Trabajan con Prius de alto millaje?','Yes. We understand that many Prius vehicles remain useful at high mileage. We evaluate the current problem and explain practical options without making unsupported promises.':'Sí. Evaluamos el problema actual y explicamos opciones prácticas sin hacer promesas sin fundamento.','How do I schedule an appointment?':'¿Cómo programo una cita?','Call 714-650-9606 or 424-474-3334, or send the appointment-request form below. Your appointment is confirmed only after the shop contacts you with availability.':'Llama al 714-650-9606 o al 424-474-3334, o envía el formulario. La cita se confirma cuando el taller te contacte.','Do you offer service in Spanish?':'¿Ofrecen servicio en español?','Spanish service is intended to be available. Please confirm language availability when you call or request your appointment.':'Sí ofrecemos atención en español. Confirma la disponibilidad al llamar o solicitar tu cita.',
'Tell us what your vehicle is doing.':'Cuéntanos qué está haciendo tu vehículo.','Send the details below. This request does not confirm an appointment; the shop will contact you to finalize availability.':'Envía los detalles. Esta solicitud no confirma una cita; el taller te contactará para confirmar disponibilidad.','Primary phone':'Teléfono principal','Second phone':'Segundo teléfono','Email':'Correo electrónico','Visit':'Visítanos','Hours':'Horario','Open in Google Maps':'Abrir en Google Maps','Vehicle unsafe to drive?':'¿No es seguro conducir el vehículo?','Do not drive it. Arrange safe transport or roadside assistance.':'No lo conduzcas. Coordina transporte seguro o asistencia en carretera.','Appointment request':'Solicitud de cita','Fields marked * are required':'Los campos con * son obligatorios','Full name *':'Nombre completo *','Phone *':'Teléfono *','Vehicle year, make & model *':'Año, marca y modelo *','Mileage':'Millaje','Service needed *':'Servicio necesario *','Choose a service':'Elige un servicio','Hybrid battery service':'Servicio de batería híbrida','Engine diagnostics / repair':'Diagnóstico / reparación de motor','Electrical diagnostics':'Diagnóstico eléctrico','Brake service':'Servicio de frenos','Traction control diagnostics':'Diagnóstico de control de tracción','Maintenance':'Mantenimiento','Other hybrid repair':'Otra reparación híbrida','Preferred date':'Fecha preferida','What are you noticing?':'¿Qué has notado?','Request appointment':'Solicitar cita','Independent hybrid and general auto repair in Hawthorne, California.':'Reparación de híbridos y servicio general en Hawthorne, California.','Explore':'Explorar','Privacy':'Privacidad','All rights reserved.':'Todos los derechos reservados.'};
Object.assign(es,{
'Traction Control Diagnostics':'Diagnóstico de control de tracción',
'Diagnosis of traction-control warning lights, wheel-speed sensors, and stability-system faults.':'Diagnóstico de luces de control de tracción, sensores de velocidad de rueda y fallas del sistema de estabilidad.',
'Traction control diagnostics':'Diagnóstico de control de tracción',
'From high-voltage battery diagnostics to brakes and traction control, we look at how the vehicle works as a complete system.':'Desde el diagnóstico de la batería de alto voltaje hasta los frenos y el control de tracción, evaluamos el vehículo como un sistema completo.',
'Call 714-650-9606 or 424-474-3334, or send the appointment-request form below. Your appointment is confirmed only after the shop contacts you with availability.':'Llama al 714-650-9606 o al 424-474-3334, o envía el formulario. La cita se confirma cuando el taller te contacte.',
'Real work at Hybrid 310':'Trabajo real en Hybrid 310',
'Hands-on hybrid experience.':'Experiencia práctica con híbridos.',
'Real repairs performed at our Hawthorne shop by technicians familiar with Toyota, Lexus, Hyundai, and Kia hybrid systems, plus select general repair.':'Reparaciones reales en nuestro taller de Hawthorne por técnicos familiarizados con sistemas híbridos Toyota, Lexus, Hyundai y Kia, además de reparación general selecta.',
'View our services':'Ver nuestros servicios',
'Prius engine service':'Servicio de motor Prius',
'Lexus hybrid service':'Servicio de híbrido Lexus',
'Prius inspection':'Inspección de Prius',
'Hybrid specialists':'Especialistas en híbridos',
'Clear diagnostics':'Diagnósticos claros',
'Expert hybrid service and general repair.':'Servicio experto de híbridos y reparación general.',
'We specialize in Toyota, Lexus, Hyundai, and Kia hybrids, along with select general repair for Toyota, Honda, Lexus, and Scion vehicles.':'Nos especializamos en híbridos Toyota, Lexus, Hyundai y Kia, además de reparación general selecta para vehículos Toyota, Honda, Lexus y Scion.',
'Check vehicle compatibility':'Verificar compatibilidad del vehículo',
'Hybrid 310 currently does not service European vehicles.':'Hybrid 310 actualmente no atiende vehículos europeos.',
'Hybrid battery, engine, brake, and electrical service.':'Servicio de batería híbrida, motor, frenos y sistema eléctrico.',
'Toyota general repair':'Reparación general Toyota',
'General repair for supported non-hybrid models.':'Reparación general para modelos no híbridos compatibles.',
'Hybrid expertise and select general repair.':'Experiencia híbrida y reparación general selecta.',
'Select diagnostics, maintenance, and repair.':'Diagnóstico, mantenimiento y reparación selecta.',
'Hybrid diagnostics, maintenance, and repair.':'Diagnóstico, mantenimiento y reparación de híbridos.',
'Hybrid diagnostics':'Diagnóstico de híbridos',
'Testing for battery, warning-light, and electrical concerns.':'Pruebas de batería, luces de advertencia y problemas eléctricos.',
'View supported models':'Ver modelos compatibles',
'See supported models':'Ver modelos compatibles',
'Battery, engine, brakes & electrical.':'Batería, motor, frenos y sistema eléctrico.',
'Service for supported non-hybrid models.':'Servicio para modelos no híbridos compatibles.',
'Hybrid expertise & general repair.':'Experiencia híbrida y reparación general.',
'Diagnostics, maintenance & repair.':'Diagnóstico, mantenimiento y reparación.',
'Battery, warning-light & electrical testing.':'Pruebas de batería, luces de advertencia y sistema eléctrico.'
,'Mon–Fri 8 AM–5 PM':'Lun–Vie 8 AM–5 PM'
,'Sat 8 AM–2 PM · Sun closed':'Sáb 8 AM–2 PM · Dom cerrado'
,'Independent hybrid repair • Hawthorne, CA':'Reparación independiente de híbridos • Hawthorne, CA'
,'Hybrid':'Especialistas'
,'specialists.':'en híbridos.'
,'Honest':'Diagnósticos'
,'diagnostics.':'honestos.'
,'Hybrid diagnostics, battery repair, electrical troubleshooting, maintenance, and select general repair for Toyota, Lexus, Honda, Hyundai, Kia, and Scion vehicles.':'Diagnóstico de híbridos, reparación de baterías, servicio eléctrico, mantenimiento y reparación general selecta para Toyota, Lexus, Honda, Hyundai, Kia y Scion.'
,'Need help today?':'¿Necesitas ayuda hoy?'
,'Honest diagnostics':'Diagnósticos honestos'
,'Toyota • Lexus • Honda • Hyundai • Kia • Scion':'Toyota • Lexus • Honda • Hyundai • Kia • Scion'
});
const originalText=new Map(),walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);
while(walker.nextNode()){const n=walker.currentNode,t=n.nodeValue.trim();if(t)originalText.set(n,t)}
const originalPlaceholders=new Map([...document.querySelectorAll('[placeholder]')].map(el=>[el,el.placeholder]));
let currentLang='en';
function setLanguage(lang){currentLang=lang==='es'?'es':'en';document.documentElement.lang=currentLang;originalText.forEach((english,node)=>{const translated=currentLang==='es'&&es[english]?es[english]:english;node.nodeValue=node.nodeValue.replace(node.nodeValue.trim(),translated)});originalPlaceholders.forEach((english,el)=>{const spanish={'e.g. 2015 Toyota Prius':'ej. Toyota Prius 2015','Warning lights, sounds, recent repairs, or other details':'Luces de advertencia, sonidos, reparaciones recientes u otros detalles'}[english];el.placeholder=currentLang==='es'&&spanish?spanish:english});document.querySelectorAll('.lang').forEach(btn=>btn.querySelectorAll('span').forEach(span=>span.classList.toggle('active',span.textContent.trim().toLowerCase()===currentLang)));document.querySelector('.menu').setAttribute('aria-label',currentLang==='es'?'Abrir menú':'Open menu');document.querySelectorAll('.lang').forEach(btn=>btn.setAttribute('aria-label',currentLang==='es'?'Cambiar idioma':'Switch language'));document.title=currentLang==='es'?'Hybrid 310 | Reparación de Prius e híbridos en Hawthorne, CA':'Hybrid 310 | Prius & Hybrid Repair in Hawthorne, CA';try{localStorage.setItem('hybrid310-language',currentLang)}catch{}}
document.querySelectorAll('.lang').forEach(btn=>btn.addEventListener('click',()=>setLanguage(currentLang==='en'?'es':'en')));
try{setLanguage(localStorage.getItem('hybrid310-language')||'en')}catch{setLanguage('en')}

const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
if(!reduceMotion){requestAnimationFrame(()=>document.body.classList.add('loaded'));const steps=document.querySelectorAll('.process li');const processObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('process-active');processObserver.unobserve(entry.target)}}),{threshold:.35});steps.forEach(step=>processObserver.observe(step))}
if(!reduceMotion){const premiumItems=document.querySelectorAll('.work-heading,.real-work-grid figure,.work-trust,.vehicle-intro,.model-card');premiumItems.forEach(item=>item.classList.add('premium-reveal'));const premiumObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('premium-visible');premiumObserver.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -30px'});premiumItems.forEach(item=>premiumObserver.observe(item))}
const header=document.querySelector('.header');
let ticking=false;
window.addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(()=>{header.classList.toggle('scrolled',window.scrollY>48);ticking=false});ticking=true}},{passive:true});
const hero=document.querySelector('.hero');
if(hero){const heroObserver=new IntersectionObserver(([entry])=>document.body.classList.toggle('hero-in-view',entry.isIntersecting),{threshold:.08});heroObserver.observe(hero)}
